# Generated by Django 4.2.20 on 2025-03-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('required_elective', 'Required Elective')], max_length=20)),
                ('grade_level', models.IntegerField()),
                ('max_students', models.IntegerField()),
                ('eligible_teachers', models.TextField(help_text="Format: 'T001|T002'")),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday')], max_length=2)),
                ('slot', models.IntegerField(help_text='Period number (1-6)')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('type', models.CharField(choices=[('classroom', 'Classroom'), ('lab', 'Laboratory'), ('gym', 'Gymnasium'), ('art', 'Art Room'), ('music', 'Music Room'), ('other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade_level', models.IntegerField()),
                ('preferences', models.TextField(help_text="Format: 'Art|Robotics'")),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('availability', models.TextField(help_text="Format: 'M1-M6,T1-T3'")),
                ('subjects', models.TextField(help_text="Format: 'Math|Science'")),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('students', models.TextField(blank=True, help_text="Format: 'S001|S002'")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.period')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher')),
            ],
            options={
                'unique_together': {('room', 'period'), ('teacher', 'period')},
            },
        ),
    ]
