# Generated by Django 4.2.20 on 2025-03-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_section_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('year', 'Year'), ('trimester', 'Trimester'), ('quarter', 'Quarter')], default='year', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='sections_needed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('required_elective', 'Required Elective'), ('language', 'Language')], max_length=20),
        ),
    ]
