# Generated by Django 4.2.20 on 2025-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_course_duration_course_sections_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='when',
            field=models.CharField(choices=[('year', 'Full Year'), ('t1', 'Trimester 1'), ('t2', 'Trimester 2'), ('t3', 'Trimester 3'), ('q1', 'Quarter 1'), ('q2', 'Quarter 2'), ('q3', 'Quarter 3'), ('q4', 'Quarter 4')], default='year', help_text='When this section is scheduled (year, trimester, quarter)', max_length=10),
        ),
    ]
