# Generated by Django 4.2.20 on 2025-03-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_section_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='section',
            name='max_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='section_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schedule.course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.room'),
        ),
        migrations.AlterField(
            model_name='section',
            name='when',
            field=models.CharField(choices=[('year', 'Full Year'), ('semester', 'Semester'), ('quarter', 'Quarter'), ('trimester', 'Trimester'), ('q1', 'Quarter 1'), ('q2', 'Quarter 2'), ('q3', 'Quarter 3'), ('q4', 'Quarter 4'), ('s1', 'Semester 1'), ('s2', 'Semester 2'), ('t1', 'Trimester 1'), ('t2', 'Trimester 2'), ('t3', 'Trimester 3')], default='year', max_length=20),
        ),
        migrations.RemoveField(
            model_name='section',
            name='students',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.student')),
            ],
            options={
                'unique_together': {('student', 'section')},
            },
        ),
        migrations.AddField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='sections', through='schedule.Enrollment', to='schedule.student'),
        ),
    ]
