# Generated by Django 4.2.20 on 2025-03-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_section_unique_together_section_max_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='period_name',
            field=models.CharField(blank=True, help_text='Descriptive name for this period', max_length=50, null=True),
        ),
    ]
