# Generated by Django 4.2.20 on 2025-03-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_period_multiple_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='slot',
            field=models.CharField(help_text='Period identifier (e.g., 1, 2, A, B, L for Lunch)', max_length=10),
        ),
    ]
