# Generated by Django 4.2.20 on 2025-03-15 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_coursegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrimesterCourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('group_type', models.CharField(choices=[('required_pair', 'Required Pair'), ('elective', 'Elective Options')], max_length=20)),
                ('courses', models.ManyToManyField(related_name='trimester_groups', to='schedule.course')),
                ('preferred_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.period')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
