# Generated by Django 4.2.20 on 2025-03-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_trimestercoursegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_students',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
