# Generated by Django 4.2.20 on 2025-03-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_make_course_max_students_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='exact_size',
            field=models.IntegerField(blank=True, help_text='If set, this section should have exactly this many students', null=True),
        ),
    ]
